### ISSUE TITLE
Repository is not participating in Hacktoberfest

### ISSUE THREAD

**Issue by Croustys** [Lynch23/javascript-Hacktoberfest2022#4]
Hacktoberfest label is not added to the repository therefore it does not participate

**Comment by Lynch23** [comment]
Issue fixed

**Comment by Croustys** [comment]
It still does not participate according to [https://hacktoberfest.com/profile/](https://hacktoberfest.com/profile/), you have to add "hacktoberfest" as a topic in the about of the repository! Hope it helps @Lynch23

**Comment by Lynch23** [comment]
Hey there, this repo was excluded from the hacktoberfest so I had to make a copy, I have updated the readme documentation with a link to the copy, I'd love it if you followed the link and made your old contribution there. The link is at the top of the read me markdown of this repository.
