### ISSUE TITLE
Repo still does not participate in Hacktoberfest

### ISSUE THREAD

**Issue by Croustys** [Lynch23/javascript-Hacktoberfest2022#5]
It still does not participate according to [https://hacktoberfest.com/profile/](https://hacktoberfest.com/profile/), you have to add "hacktoberfest" as a topic in the about of the repository! Hope it helps!

**Comment by Lynch23** [comment]
My apologies, I did not understand how to fix the issue, I have added "hacktoberfest" and "hacktoberfest-accepted" labels, I hope that fixes the issue

**Comment by Croustys** [comment]
All good, you solved it perfectly now! Happy Hacktoberfest! <3

**Comment by Lynch23** [comment]
Perfect! thank you and Happy Hacktoberfest!
